{"name": "Логин курьером с несуществующими данными", "status": "passed", "description": "Проверяем, что нельзя залогиниться несуществующими курьером, допустим, в логине, и что приходит ответ 404 с соответствующим письменным уведомлением", "steps": [{"name": "Создание рандомных регистрационных данных", "status": "passed", "start": 1715622401601, "stop": 1715622401601}], "start": 1715622401600, "stop": 1715622402003, "uuid": "1f91be43-0869-4ca7-be1d-7ae6c448bf4e", "historyId": "66785b1c126aadbdccd73d6a3ddc1fcf", "testCaseId": "66785b1c126aadbdccd73d6a3ddc1fcf", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_without_registration", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-SSVUBLG9"}, {"name": "thread", "value": "4748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}